# Complete NumPy Guide: From Basics to Advanced

## Table of Contents
1. Introduction to NumPy
2. Why NumPy is Faster
3. Installation and Imports
4. NumPy Arrays
5. Array Creation Methods
6. Array Attributes and Properties
7. Array Indexing and Slicing
8. Array Operations
9. Mathematical Functions
10. Linear Algebra
11. Random Number Generation
12. Shape Manipulation
13. Broadcasting
14. Advanced Functions
15. File I/O Operations

In [ ]:
# Import NumPy
import numpy as np

# Removed unused import 'plt'

print("NumPy Version:", np.__version__)
print("NumPy Installation: Successful")

NumPy Version: 2.4.2
NumPy Installation: Successful


## 1. What is NumPy?

**NumPy (Numerical Python)** is a Python library for numerical computing that provides:
- Support for large, multi-dimensional arrays and matrices
- High-level mathematical functions for array operations
- Tools for integrating C/C++ and Fortran code
- Linear algebra, Fourier transform, and random number capabilities

**Key Features:**
- **Arrays**: N-dimensional arrays (ndarrays) for homogeneous data
- **Performance**: Operations are implemented in C for speed
- **Convenience**: Easy syntax for mathematical operations
- **Compatibility**: Works seamlessly with other libraries like Pandas, SciPy, Matplotlib

## 2. Why is NumPy Faster than Python Lists?

### Performance Reasons:

1. **Fixed Data Type**: NumPy arrays store elements of a single data type in contiguous memory, while Python lists are arrays of pointers to objects scattered in memory.

2. **Memory Efficiency**: NumPy arrays consume much less memory because they store raw data directly without object overhead.

3. **C Implementation**: NumPy operations are implemented in C and optimized for performance, while Python lists use pure Python which is interpreted.

4. **No Type Checking**: Since NumPy arrays have a fixed type, there's no overhead of type checking during operations.

5. **Vectorization**: NumPy allows vectorized operations that operate on entire arrays without explicit loops in Python.

6. **CPU Caching**: Contiguous memory access patterns improve CPU cache utilization.

### Performance Comparison:

In [ ]:
import time

# Performance Comparison: NumPy vs Python List
size = 1000000

# Using Python List
python_list = list(range(size))
start = time.time()
result_list = [x * 2 for x in python_list]
time_list = time.time() - start

# Using NumPy Array
numpy_array = np.arange(size)
start = time.time()
result_numpy = numpy_array * 2
time_numpy = time.time() - start

print(f"Python List Time: {time_list:.6f} seconds")
print(f"NumPy Array Time: {time_numpy:.6f} seconds")
print(f"Speed Improvement: {time_list/time_numpy:.2f}x faster")

Python List Time: 0.055978 seconds
NumPy Array Time: 0.003050 seconds
Speed Improvement: 18.35x faster


## 3. Creating NumPy Arrays

NumPy provides multiple ways to create arrays for different purposes:

In [ ]:
# ===== ARRAY CREATION METHODS =====

# 1. From Python List
arr1 = np.array([1, 2, 3, 4, 5])
print("From List:\n", arr1)

# 2. From nested list (2D array)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# 3. Using np.arange(start, stop, step) - similar to range()
arr3 = np.arange(0, 10, 2)
print("\nUsing arange:\n", arr3)

# 4. Using np.linspace(start, stop, num) - evenly spaced numbers
arr4 = np.linspace(0, 10, 5)
print("\nUsing linspace:\n", arr4)

# 5. Using np.logspace() - logarithmically spaced numbers
arr5 = np.logspace(0, 2, 5)
print("\nUsing logspace:\n", arr5)

# 6. Using np.zeros() - array of zeros
arr6 = np.zeros((3, 3))
print("\nZeros (3x3):\n", arr6)

# 7. Using np.ones() - array of ones
arr7 = np.ones((2, 3))
print("\nOnes (2x3):\n", arr7)

# 8. Using np.full() - array filled with specific value
arr8 = np.full((3, 3), 7)
print("\nFull with 7s:\n", arr8)

# 9. Using np.eye() - identity matrix
arr9 = np.eye(3)
print("\nIdentity Matrix:\n", arr9)

# 10. Using np.empty() - uninitialized array
arr10 = np.empty((2, 2))
print("\nEmpty (2x2):\n", arr10)

# 11. Using np.diag() - diagonal array from sequence
arr11 = np.diag([1, 2, 3])
print("\nDiagonal Array:\n", arr11)

# 12. Using np.tile() - repeat array
arr12 = np.tile([1, 2, 3], 3)
print("\nTiled Array:\n", arr12)

# 13. Using np.repeat() - repeat elements
arr13 = np.repeat([1, 2, 3], 3)
print("\nRepeat Array:\n", arr13)

From List:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

Using arange:
 [0 2 4 6 8]

Using linspace:
 [ 0.   2.5  5.   7.5 10. ]

Using logspace:
 [  1.           3.16227766  10.          31.6227766  100.        ]

Zeros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

Full with 7s:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Empty (2x2):
 [[ 2.5  5. ]
 [ 7.5 10. ]]

Diagonal Array:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Tiled Array:
 [1 2 3 1 2 3 1 2 3]

Repeat Array:
 [1 1 1 2 2 2 3 3 3]


## 4. Array Attributes and Data Types

Every NumPy array has important attributes that describe its properties:

In [ ]:
# ===== ARRAY ATTRIBUTES =====

arr = np.array([[1, 2, 3], [4, 5, 6]])

# 1. shape - dimensions of array
print("Shape:", arr.shape)

# 2. size - total number of elements
print("Size:", arr.size)

# 3. dtype - data type of elements
print("Data Type:", arr.dtype)

# 4. ndim - number of dimensions
print("Number of Dimensions:", arr.ndim)

# 5. itemsize - size of one element in bytes
print("Item Size (bytes):", arr.itemsize)

# 6. nbytes - total memory used
print("Total Bytes:", arr.nbytes)

# 7. strides - bytes to move to next element in each dimension
print("Strides:", arr.strides)

# ===== DATA TYPES =====
print("\n--- Data Types ---")

# Different data types
dt_int = np.array([1, 2, 3], dtype=np.int32)
dt_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
dt_complex = np.array([1+2j, 3+4j], dtype=np.complex128)
dt_bool = np.array([True, False, True], dtype=np.bool_)
dt_str = np.array(['a', 'b', 'c'], dtype=np.str_)

print("int32:", dt_int.dtype)
print("float64:", dt_float.dtype)
print("complex128:", dt_complex.dtype)
print("bool:", dt_bool.dtype)
print("str:", dt_str.dtype)

# Type conversion with astype()
arr_int = np.array([1, 2, 3])
arr_float = arr_int.astype(np.float64)
print("\nConverted to float:", arr_float, "dtype:", arr_float.dtype)

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2
Item Size (bytes): 8
Total Bytes: 48
Strides: (24, 8)

--- Data Types ---
int32: int32
float64: float64
complex128: complex128
bool: bool
str: <U1

Converted to float: [1. 2. 3.] dtype: float64


## 5. Indexing and Slicing

NumPy arrays support advanced indexing and slicing similar to Python lists but with more power:

In [ ]:
# ===== INDEXING AND SLICING =====

# 1D Array Indexing
arr1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1d)
print("Element at index 0:", arr1d[0])
print("Element at index -1:", arr1d[-1])
print("Slice [1:3]:", arr1d[1:3])
print("Slice [::2]:", arr1d[::2])
print("Slice [::-1]:", arr1d[::-1])  # Reverse

# 2D Array Indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr2d)
print("Element at [0, 1]:", arr2d[0, 1])
print("Row 1:", arr2d[1])
print("Column 1:", arr2d[:, 1])
print("Slice [1:3, 1:3]:\n", arr2d[1:3, 1:3])

# Boolean Indexing
print("\n--- Boolean Indexing ---")
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print("Array:", arr)
print("Mask (arr > 25):", mask)
print("Elements > 25:", arr[mask])

# Fancy Indexing
print("\n--- Fancy Indexing ---")
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
print("Indices:", indices)
print("arr[indices]:", arr[indices])

# 2D Fancy Indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 1, 2])
cols = np.array([0, 1, 2])
print("\nDiagonal elements:", arr2d[rows, cols])

# Using np.where() for conditional indexing
print("\n--- np.where() ---")
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 3)
print("Indices where arr > 3:", result)
print("Values where arr > 3:", arr[result])

1D Array: [10 20 30 40 50]
Element at index 0: 10
Element at index -1: 50
Slice [1:3]: [20 30]
Slice [::2]: [10 30 50]
Slice [::-1]: [50 40 30 20 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at [0, 1]: 2
Row 1: [4 5 6]
Column 1: [2 5 8]
Slice [1:3, 1:3]:
 [[5 6]
 [8 9]]

--- Boolean Indexing ---
Array: [10 20 30 40 50]
Mask (arr > 25): [False False  True  True  True]
Elements > 25: [30 40 50]

--- Fancy Indexing ---
Indices: [0 2 4]
arr[indices]: [10 30 50]

Diagonal elements: [1 5 9]

--- np.where() ---
Indices where arr > 3: (array([3, 4]),)
Values where arr > 3: [4 5]


## 6. Arithmetic Operations

NumPy supports element-wise operations on arrays:

In [ ]:
# ===== ARITHMETIC OPERATIONS =====

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)

# Basic arithmetic operations
print("\nAddition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (b / a):", b / a)
print("Floor Division (b // a):", b // a)
print("Modulo (b % a):", b % a)
print("Exponentiation (a ** 2):", a ** 2)

# Operations with scalars
print("\n--- Operations with Scalars ---")
print("a + 10:", a + 10)
print("a * 2:", a * 2)
print("10 / a:", 10 / a)

# In-place operations
print("\n--- In-place Operations ---")
c = np.array([1, 2, 3])
print("Original c:", c)
c += 10  # c = c + 10
print("After c += 10:", c)

# ===== MATHEMATICAL FUNCTIONS =====
print("\n--- Universal Functions (ufuncs) ---")

arr = np.array([0, 1, 2, 3, 4, 5])

# Power and logarithmic functions
print("np.sqrt(arr):", np.sqrt(arr.astype(float)))
print("np.square(arr):", np.square(arr))
print("np.power(arr, 2):", np.power(arr, 2))

# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print("\nnp.sin(angles):", np.sin(angles))
print("np.cos(angles):", np.cos(angles))
print("np.tan(angles):", np.tan(angles))

# Hyperbolic functions
print("\nnp.sinh(arr):", np.sinh(arr))
print("np.cosh(arr):", np.cosh(arr))

# Exponential and logarithmic
arr_exp = np.array([1, 2, 3, 4, 5])
print("\nnp.exp(arr_exp):", np.exp(arr_exp))
print("np.log(arr_exp):", np.log(arr_exp))
print("np.log10(arr_exp):", np.log10(arr_exp))
print("np.log2(arr_exp):", np.log2(arr_exp))

# Rounding functions
arr_float = np.array([3.14, 2.71, 1.41, 4.87])
print("\n--- Rounding ---")
print("np.ceil(arr_float):", np.ceil(arr_float))
print("np.floor(arr_float):", np.floor(arr_float))
print("np.round(arr_float):", np.round(arr_float))

# Absolute value
arr_neg = np.array([-1, -2, 3, -4, 5])
print("\nnp.abs(arr_neg):", np.abs(arr_neg))

Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]

Addition (a + b): [11 22 33 44 55]
Subtraction (a - b): [ -9 -18 -27 -36 -45]
Multiplication (a * b): [ 10  40  90 160 250]
Division (b / a): [10. 10. 10. 10. 10.]
Floor Division (b // a): [10 10 10 10 10]
Modulo (b % a): [0 0 0 0 0]
Exponentiation (a ** 2): [ 1  4  9 16 25]

--- Operations with Scalars ---
a + 10: [11 12 13 14 15]
a * 2: [ 2  4  6  8 10]
10 / a: [10.          5.          3.33333333  2.5         2.        ]

--- In-place Operations ---
Original c: [1 2 3]
After c += 10: [11 12 13]

--- Universal Functions (ufuncs) ---
np.sqrt(arr): [0.         1.         1.41421356 1.73205081 2.         2.23606798]
np.square(arr): [ 0  1  4  9 16 25]
np.power(arr, 2): [ 0  1  4  9 16 25]

np.sin(angles): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
np.cos(angles): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
np.tan(angles): [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

np.sinh(arr): [ 0.          1.17520119  3.62686041 10.01787493 27.2

## 7. Aggregation & Statistical Functions

Functions that reduce arrays to single values or arrays with fewer dimensions:

In [ ]:
# ===== AGGREGATION FUNCTIONS =====

arr = np.array([1, 2, 3, 4, 5, 6])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:", arr)
print("2D Array:\n", arr2d)

# Basic aggregation functions
print("\n--- Basic Aggregation ---")
print("np.sum(arr):", np.sum(arr))
print("np.prod(arr):", np.prod(arr))
print("np.mean(arr):", np.mean(arr))
print("np.median(arr):", np.median(arr))
print("np.std(arr):", np.std(arr))  # Standard deviation
print("np.var(arr):", np.var(arr))  # Variance

# Find minimum and maximum
print("\n--- Min/Max ---")
print("np.min(arr):", np.min(arr))
print("np.max(arr):", np.max(arr))
print("np.argmin(arr):", np.argmin(arr))  # Index of minimum
print("np.argmax(arr):", np.argmax(arr))  # Index of maximum

# Aggregation along axes
print("\n--- Aggregation Along Axes (2D) ---")
print("Sum along axis 0 (rows):", np.sum(arr2d, axis=0))
print("Sum along axis 1 (columns):", np.sum(arr2d, axis=1))
print("Mean along axis 0:", np.mean(arr2d, axis=0))
print("Mean along axis 1:", np.mean(arr2d, axis=1))

# Cumulative functions
print("\n--- Cumulative Functions ---")
print("np.cumsum(arr):", np.cumsum(arr))  # Cumulative sum
print("np.cumprod(arr):", np.cumprod(arr))  # Cumulative product

# Percentiles and quantiles
print("\n--- Percentiles ---")
print("25th percentile:", np.percentile(arr, 25))
print("50th percentile:", np.percentile(arr, 50))
print("75th percentile:", np.percentile(arr, 75))

# Unique values and counting
print("\n--- Unique Values ---")
arr_dup = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
print("Array:", arr_dup)
print("Unique values:", np.unique(arr_dup))
unique, counts = np.unique(arr_dup, return_counts=True)
print("Values and counts:", list(zip(unique, counts)))

1D Array: [1 2 3 4 5 6]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Basic Aggregation ---
np.sum(arr): 21
np.prod(arr): 720
np.mean(arr): 3.5
np.median(arr): 3.5
np.std(arr): 1.707825127659933
np.var(arr): 2.9166666666666665

--- Min/Max ---
np.min(arr): 1
np.max(arr): 6
np.argmin(arr): 0
np.argmax(arr): 5

--- Aggregation Along Axes (2D) ---
Sum along axis 0 (rows): [12 15 18]
Sum along axis 1 (columns): [ 6 15 24]
Mean along axis 0: [4. 5. 6.]
Mean along axis 1: [2. 5. 8.]

--- Cumulative Functions ---
np.cumsum(arr): [ 1  3  6 10 15 21]
np.cumprod(arr): [  1   2   6  24 120 720]

--- Percentiles ---
25th percentile: 2.25
50th percentile: 3.5
75th percentile: 4.75

--- Unique Values ---
Array: [1 2 2 3 3 3 4 4 4 4]
Unique values: [1 2 3 4]
Values and counts: [(np.int64(1), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(4))]


## 8. Linear Algebra Operations

NumPy provides functions for matrix algebra in `np.linalg` module:

In [ ]:
# ===== LINEAR ALGEBRA =====

# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([1, 2])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Vector v:", v)

# Matrix multiplication
print("\n--- Matrix Multiplication ---")
print("np.dot(A, B):\n", np.dot(A, B))
print("A @ B:\n", A @ B)  # @ operator for matrix multiplication
print("np.dot(A, v):", np.dot(A, v))

# Transpose
print("\n--- Transpose ---")
print("A.T:\n", A.T)
print("np.transpose(A):\n", np.transpose(A))

# Determinant
print("\n--- Determinant ---")
print("np.linalg.det(A):", np.linalg.det(A))

# Inverse
print("\n--- Inverse ---")
print("np.linalg.inv(A):\n", np.linalg.inv(A))

# Rank
print("\n--- Rank ---")
print("np.linalg.matrix_rank(A):", np.linalg.matrix_rank(A))

# Eigenvalues and eigenvectors
print("\n--- Eigenvalues and Eigenvectors ---")
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Trace (sum of diagonal elements)
print("\n--- Trace ---")
print("np.trace(A):", np.trace(A))

# Solving linear equations: Ax = B
print("\n--- Solving Linear Equations ---")
A_solve = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A_solve, b)
print("Solution x:", x)
print("Verification A @ x:", A_solve @ x)

# SVD (Singular Value Decomposition)
print("\n--- SVD ---")
U, S, Vt = np.linalg.svd(A)
print("U:\n", U)
print("Singular values:", S)
print("Vt:\n", Vt)

# QR Decomposition
print("\n--- QR Decomposition ---")
Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Vector v: [1 2]

--- Matrix Multiplication ---
np.dot(A, B):
 [[19 22]
 [43 50]]
A @ B:
 [[19 22]
 [43 50]]
np.dot(A, v): [ 5 11]

--- Transpose ---
A.T:
 [[1 3]
 [2 4]]
np.transpose(A):
 [[1 3]
 [2 4]]

--- Determinant ---
np.linalg.det(A): -2.0000000000000004

--- Inverse ---
np.linalg.inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]

--- Rank ---
np.linalg.matrix_rank(A): 2

--- Eigenvalues and Eigenvectors ---
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

--- Trace ---
np.trace(A): 5

--- Solving Linear Equations ---
Solution x: [2. 3.]
Verification A @ x: [9. 8.]

--- SVD ---
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

--- QR Decomposition ---
Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


## 9. Random Number Generation

NumPy provides comprehensive random number generation capabilities:

In [ ]:
# ===== RANDOM NUMBER GENERATION =====

# Set seed for reproducibility
np.random.seed(42)

print("--- Basic Random Numbers ---")
# Uniform distribution [0, 1)
print("np.random.rand(5):", np.random.rand(5))
print("np.random.rand(2, 3):\n", np.random.rand(2, 3))

# Standard normal distribution
print("\nnp.random.randn(5):", np.random.randn(5))

# Random integers
print("\nnp.random.randint(0, 10, size=5):", np.random.randint(0, 10, size=5))
print("np.random.randint(1, 7, size=(2, 3)):\n", np.random.randint(1, 7, size=(2, 3)))

# Distributions
print("\n--- Distributions ---")

# Normal distribution
print("Normal(mean=0, std=1):", np.random.normal(0, 1, size=5))
print("Normal(mean=100, std=15):", np.random.normal(100, 15, size=5))

# Uniform distribution
print("Uniform(0, 1):", np.random.uniform(0, 1, size=5))
print("Uniform(10, 20):", np.random.uniform(10, 20, size=5))

# Binomial distribution
print("Binomial(n=10, p=0.5):", np.random.binomial(10, 0.5, size=5))

# Poisson distribution
print("Poisson(lambda=3):", np.random.poisson(3, size=5))
    
# Exponential distribution
print("Exponential(lambda=1):", np.random.exponential(1, size=5))

# Chi-square distribution
print("Chi-square(df=2):", np.random.chisquare(2, size=5))

# Choose and shuffle
print("\n--- Choice and Shuffle ---")
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)

# Random choice with replacement
choices = np.random.choice(arr, size=5)
print("Random choice (with replacement):", choices)

# Random choice without replacement
choices_unique = np.random.choice(arr, size=3, replace=False)
print("Random choice (without replacement):", choices_unique)

# Shuffle
arr_shuffle = arr.copy()
np.random.shuffle(arr_shuffle)
print("Shuffled:", arr_shuffle)

--- Basic Random Numbers ---
np.random.rand(5): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
np.random.rand(2, 3):
 [[0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449]]

np.random.randn(5): [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]

np.random.randint(0, 10, size=5): [0 9 2 6 3]
np.random.randint(1, 7, size=(2, 3)):
 [[1 3 5]
 [3 5 1]]

--- Distributions ---
Normal(mean=0, std=1): [ 0.95036968 -0.60063869 -0.29169375 -0.60170661  1.85227818]
Normal(mean=100, std=15): [ 99.79754163  84.13433607 112.33817368  81.68734525 103.13295393]
Uniform(0, 1): [0.54671028 0.18485446 0.96958463 0.77513282 0.93949894]
Uniform(10, 20): [18.9482735  15.97899979 19.21874235 10.88492502 11.95982862]
Binomial(n=10, p=0.5): [2 4 5 4 7]
Poisson(lambda=3): [3 3 1 4 1]
Exponential(lambda=1): [1.98852957 0.97630119 0.4018188  0.06566807 0.37248835]
Chi-square(df=2): [0.78662843 2.61575157 2.02977872 4.36450382 1.27813227]

--- Choice and Shuffle ---
Original: 

## 10. Shape Manipulation

Operations to change the shape and structure of arrays:

In [ ]:
# ===== SHAPE MANIPULATION =====

# Reshape
arr = np.arange(12)
print("Original array:", arr)
print("Shape:", arr.shape)

reshaped = arr.reshape(3, 4)
print("\nReshaped (3, 4):\n", reshaped)

reshaped_3d = arr.reshape(2, 3, 2)
print("\nReshaped (2, 3, 2):\n", reshaped_3d)

# Flatten
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2d)
print("Flattened:", arr2d.flatten())
print("Ravel (flattened view):", arr2d.ravel())

# Transpose (already covered but important)
print("\nTransposed:\n", arr2d.T)

# Squeeze (remove axes of length 1)
arr_squeeze = np.array([[[1, 2], [3, 4]]])
print("\nBefore squeeze shape:", arr_squeeze.shape)
squeezed = np.squeeze(arr_squeeze)
print("After squeeze shape:", squeezed.shape)

# Expand_dims (add new axis)
arr = np.array([1, 2, 3])
print("\nOriginal shape:", arr.shape)
expanded = np.expand_dims(arr, axis=0)
print("After expand_dims(axis=0) shape:", expanded.shape)
print("Result:\n", expanded)

# Stack and concatenate
print("\n--- Stack and Concatenate ---")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Original arrays: a =", a, ", b =", b)

# Concatenate
concat = np.concatenate([a, b])
print("Concatenate:", concat)

# Stack (new dimension)
stacked = np.stack([a, b])
print("Stack:\n", stacked)

# vstack (vertical stack / row-wise)
vstacked = np.vstack([a, b])
print("VStack:\n", vstacked)

# hstack (horizontal stack / column-wise)
hstacked = np.hstack([a, b])
print("HStack:", hstacked)

# Split arrays
arr = np.array([1, 2, 3, 4, 5, 6])
print("\nOriginal array:", arr)
split = np.array_split(arr, 3)
print("Split into 3 parts:", split)

# Split 2D array
arr2d = np.arange(12).reshape(3, 4)
print("\n2D array:\n", arr2d)
hsplit = np.hsplit(arr2d, 2)
print("Horizontal split:\n", hsplit)

# Roll (roll elements)
arr = np.array([1, 2, 3, 4, 5])
print("\nOriginal:", arr)
print("Roll by 2:", np.roll(arr, 2))

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (2, 3, 2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

2D Array:
 [[1 2 3]
 [4 5 6]]
Flattened: [1 2 3 4 5 6]
Ravel (flattened view): [1 2 3 4 5 6]

Transposed:
 [[1 4]
 [2 5]
 [3 6]]

Before squeeze shape: (1, 2, 2)
After squeeze shape: (2, 2)

Original shape: (3,)
After expand_dims(axis=0) shape: (1, 3)
Result:
 [[1 2 3]]

--- Stack and Concatenate ---
Original arrays: a = [1 2 3] , b = [4 5 6]
Concatenate: [1 2 3 4 5 6]
Stack:
 [[1 2 3]
 [4 5 6]]
VStack:
 [[1 2 3]
 [4 5 6]]
HStack: [1 2 3 4 5 6]

Original array: [1 2 3 4 5 6]
Split into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]

2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Horizontal split:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

Original: [1 2 3 4 5]
Roll by 2: [4 5 1 2 3]


## 11. Broadcasting

Broadcasting is NumPy's mechanism for performing operations on arrays of different shapes:

In [ ]:
# ===== BROADCASTING =====

# Example 1: Scalar and Array
print("--- Example 1: Scalar and Array ---")
arr = np.array([1, 2, 3, 4, 5])
scalar = 10
result = arr + scalar
print(f"Array: {arr}")
print(f"Scalar: {scalar}")
print(f"Result (arr + scalar): {result}")

# Example 2: Different shapes
print("\n--- Example 2: Different shapes ---")
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([10, 20, 30])  # Shape: (3,)
result = arr1 + arr2
print(f"Array 1 shape: {arr1.shape}\n{arr1}")
print(f"Array 2 shape: {arr2.shape}\n{arr2}")
print(f"Result:\n{result}")

# Example 3: Column vector and row vector
print("\n--- Example 3: Column vector and row vector ---")
col_vector = np.array([[1], [2], [3]])  # Shape: (3, 1)
row_vector = np.array([10, 20, 30, 40])  # Shape: (4,)
result = col_vector + row_vector
print(f"Column vector shape: {col_vector.shape}\n{col_vector}")
print(f"Row vector shape: {row_vector.shape}\n{row_vector}")
print(f"Result shape: {result.shape}\n{result}")

# Example 4: Using np.newaxis for explicit broadcasting
print("\n--- Example 4: Using np.newaxis ---")
a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([10, 20, 30, 40])  # Shape: (4,)
# Can't add directly, but can reshape using newaxis
a_reshaped = a[:, np.newaxis]  # Shape: (3, 1)
result = a_reshaped + b  # Result shape: (3, 4)
print(f"a shape: {a.shape}")
print(f"a reshaped shape: {a_reshaped.shape}\n{a_reshaped}")
print(f"b shape: {b.shape}")
print(f"Result shape: {result.shape}\n{result}")

--- Example 1: Scalar and Array ---
Array: [1 2 3 4 5]
Scalar: 10
Result (arr + scalar): [11 12 13 14 15]

--- Example 2: Different shapes ---
Array 1 shape: (2, 3)
[[1 2 3]
 [4 5 6]]
Array 2 shape: (3,)
[10 20 30]
Result:
[[11 22 33]
 [14 25 36]]

--- Example 3: Column vector and row vector ---
Column vector shape: (3, 1)
[[1]
 [2]
 [3]]
Row vector shape: (4,)
[10 20 30 40]
Result shape: (3, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]

--- Example 4: Using np.newaxis ---
a shape: (3,)
a reshaped shape: (3, 1)
[[1]
 [2]
 [3]]
b shape: (4,)
Result shape: (3, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


## 12. Sorting and Searching

Functions for sorting arrays and finding elements:

In [ ]:
# ===== SORTING AND SEARCHING =====

# Sorting
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
print("Original array:", arr)

# Sort (returns sorted array)
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

# Argsort (returns indices that would sort array)
indices = np.argsort(arr)
print("Indices that sort array:", indices)

# 2D Array sorting
arr2d = np.array([[3, 2], [1, 4], [2, 1]])
print("\n2D Array:\n", arr2d)
print("Sorted along axis 0:\n", np.sort(arr2d, axis=0))
print("Sorted along axis 1:\n", np.sort(arr2d, axis=1))

# Searching and filtering
print("\n--- Searching and Filtering ---")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array:", arr)

# searchsorted - find insertion positions
value = 5.5
position = np.searchsorted(arr, value)
print(f"Position to insert {value}:", position)

# nonzero - find non-zero elements
arr_special = np.array([0, 1, 0, 2, 0, 3, 4, 0])
nonzero_indices = np.nonzero(arr_special)
print("\nArray:", arr_special)
print("Indices of non-zero elements:", nonzero_indices[0])

# extract - extract elements based on condition
condition = arr > 5
print("\nCondition (arr > 5):", condition)
print("Extracted elements:", np.extract(condition, arr))

# Top-k elements
print("\n--- Top-k Elements ---")
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
top_3_indices = np.argsort(-arr)[:3]  # Negative for descending
print("Array:", arr)
print("Top 3 indices:", top_3_indices)
print("Top 3 values:", arr[top_3_indices])

Original array: [3 1 4 1 5 9 2 6 5 3]
Sorted array: [1 1 2 3 3 4 5 5 6 9]
Indices that sort array: [1 3 6 0 9 2 8 4 7 5]

2D Array:
 [[3 2]
 [1 4]
 [2 1]]
Sorted along axis 0:
 [[1 1]
 [2 2]
 [3 4]]
Sorted along axis 1:
 [[2 3]
 [1 4]
 [1 2]]

--- Searching and Filtering ---
Array: [ 1  2  3  4  5  6  7  8  9 10]
Position to insert 5.5: 5

Array: [0 1 0 2 0 3 4 0]
Indices of non-zero elements: [1 3 5 6]

Condition (arr > 5): [False False False False False  True  True  True  True  True]
Extracted elements: [ 6  7  8  9 10]

--- Top-k Elements ---
Array: [3 1 4 1 5 9 2 6]
Top 3 indices: [5 7 4]
Top 3 values: [9 6 5]


## 13. Applying Functions (Using apply_along_axis)

NumPy allows applying custom functions to arrays:

In [ ]:
# ===== APPLYING FUNCTIONS =====

# apply_along_axis
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", arr)

# Define custom function
def sum_of_squares(x):
    return np.sum(x**2)

# Apply along axis 0 (columns)
result_axis0 = np.apply_along_axis(sum_of_squares, 0, arr)
print("\nSum of squares along axis 0:", result_axis0)

# Apply along axis 1 (rows)
result_axis1 = np.apply_along_axis(sum_of_squares, 1, arr)
print("Sum of squares along axis 1:", result_axis1)

# Using vectorize (converting function to ufunc)
print("\n--- np.vectorize ---")
def custom_func(x):
    if x % 2 == 0:
        return "even"
    else:
        return "odd"

# Vectorize the function
vfunc = np.vectorize(custom_func)
arr_int = np.array([1, 2, 3, 4, 5, 6])
result = vfunc(arr_int)
print("Array:", arr_int)
print("Even/Odd:", result)

# Using piecewise
print("\n--- np.piecewise ---")
x = np.array([1, 2, 3, 4, 5])
conditions = [x < 2, x >= 4]
# Use lambda functions to apply operations element-wise
choices = [lambda x: x*2, lambda x: x**2]
result = np.piecewise(x, conditions, [lambda xi: xi*2, lambda xi: xi**2])
print("x:", x)
print("Result:", result)

# Using where for conditional operations
print("\n--- np.where ---")
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
condition = a > 2
result = np.where(condition, a, b)
print("a:", a)
print("b:", b)
print("Condition (a > 2):", condition)
print("Result (a where True, b where False):", result)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of squares along axis 0: [ 66  93 126]
Sum of squares along axis 1: [ 14  77 194]

--- np.vectorize ---
Array: [1 2 3 4 5 6]
Even/Odd: ['odd' 'even' 'odd' 'even' 'odd' 'even']

--- np.piecewise ---
x: [1 2 3 4 5]
Result: [ 2  0  0 16 25]

--- np.where ---
a: [1 2 3 4 5]
b: [10 20 30 40 50]
Condition (a > 2): [False False  True  True  True]
Result (a where True, b where False): [10 20  3  4  5]


## 14. File I/O Operations

Saving and loading arrays from files:

In [ ]:
# ===== FILE I/O =====

import os

# Save and load binary format (.npy)
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Save as .npy file
np.save('array.npy', arr)
print("Array saved to 'array.npy'")

# Load from .npy file
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

# Save multiple arrays as compressed archive (.npz)
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5], [6, 7]])
print("\n--- Multiple Arrays ---")
print("Array 1:", arr1)
print("Array 2:\n", arr2)

np.savez('arrays.npz', arr1=arr1, arr2=arr2)
print("Saved to 'arrays.npz'")

# Load from .npz file
loaded = np.load('arrays.npz')
print("Keys in npz:", loaded.files)
print("arr1:", loaded['arr1'])
print("arr2:\n", loaded['arr2'])

# Save as text file (.txt)
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('array.txt', arr, fmt='%d')
print("\n--- Text Format ---")
print("Saved to 'array.txt'")

# Load from text file
loaded_txt = np.loadtxt('array.txt')
print("Loaded from text:")
print(loaded_txt)

# Save as CSV with delimiter
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('array.csv', arr, delimiter=',', fmt='%d')
print("\nSaved to 'array.csv'")

# Load CSV
loaded_csv = np.loadtxt('array.csv', delimiter=',')
print("Loaded CSV:")
print(loaded_csv)

# Clean up
print("\n--- Cleanup ---")
files_to_remove = ['array.npy', 'arrays.npz', 'array.txt', 'array.csv']
for f in files_to_remove:
    try:
        if os.path.exists(f):
            os.remove(f)
            print(f"Removed {f}")
    except PermissionError:
        print(f"Could not remove {f} because it is being used by another process.")

print("All saved files have been cleaned up.")

Original array: [1 2 3 4 5]
Array saved to 'array.npy'
Loaded array: [1 2 3 4 5]

--- Multiple Arrays ---
Array 1: [1 2 3]
Array 2:
 [[4 5]
 [6 7]]
Saved to 'arrays.npz'
Keys in npz: ['arr1', 'arr2']
arr1: [1 2 3]
arr2:
 [[4 5]
 [6 7]]

--- Text Format ---
Saved to 'array.txt'
Loaded from text:
[[1. 2. 3.]
 [4. 5. 6.]]

Saved to 'array.csv'
Loaded CSV:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

--- Cleanup ---
Removed array.npy
Could not remove arrays.npz because it is being used by another process.
Removed array.txt
Removed array.csv
All saved files have been cleaned up.


## 15. Advanced NumPy Tips and Tricks

Useful techniques for optimizing NumPy code:

In [ ]:
# ===== ADVANCED TIPS AND TRICKS =====

# 1. Memory layout: C-contiguous vs Fortran-contiguous
print("--- Memory Layout ---")
arr_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')  # Row-major
arr_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')  # Column-major
print("C-contiguous:", arr_c.flags['C_CONTIGUOUS'])
print("Fortran-contiguous:", arr_c.flags['F_CONTIGUOUS'])
print("F-contiguous array:", arr_f.flags['F_CONTIGUOUS'])

# 2. Memory views (no copy)
print("\n--- Memory Views (No Copy) ---")
arr = np.array([1, 2, 3, 4, 5])
view = arr[1:4]
view[0] = 999  # Modifies original
print("Original array after modifying view:", arr)

# 3. Copy
print("\n--- Copy (Independent) ---")
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr[1:4].copy()
copy_arr[0] = 999  # Does NOT modify original
print("Original array after modifying copy:", arr)

# 4. Comparing arrays
print("\n--- Array Comparison ---")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([1, 2, 3, 4, 6])
print("arr1 == arr2 (element-wise):", arr1 == arr2)
print("np.array_equal(arr1, arr2):", np.array_equal(arr1, arr2))
print("np.array_equal(arr1, arr3):", np.array_equal(arr1, arr3))
print("np.allclose(arr1, arr2):", np.allclose(arr1, arr2))

# 5. Masking and advanced indexing
print("\n--- Masking ---")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = (arr > 3) & (arr < 8)
print("Array:", arr)
print("Mask (3 < arr < 8):", mask)
print("Masked values:", arr[mask])

# 6. Element-wise string operations
print("\n--- String Operations ---")
arr = np.array(['hello', 'world', 'numpy'])
print("Original:", arr)
print("Uppercase:", np.char.upper(arr))
print("Replace 'o' with '0':", np.char.replace(arr, 'o', '0'))
print("String length:", np.char.str_len(arr))

# 7. Structured arrays (like records)
print("\n--- Structured Arrays ---")
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 75.3), ('Charlie', 35, 80.2)], dtype=dt)
print(data)
print("Names:", data['name'])
print("Ages:", data['age'])

# 8. Matrix operations (deprecated but still used)
print("\n--- Matrix Operations ---")
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)
print("Matrix multiplication (@ operator):\n", m1 @ m2)
print("Element-wise multiplication:\n", m1 * m2)

# 9. Using stride tricks for efficient operations
print("\n--- Stride Tricks ---")
arr = np.arange(10)
print("Original array:", arr)
# Create a sliding window view
from numpy.lib.stride_tricks import as_strided
window_size = 3
windows = as_strided(arr, shape=(len(arr)-window_size+1, window_size), 
                      strides=(arr.strides[0], arr.strides[0]))
print("Sliding windows of size 3:\n", windows)

# 10. Partitioning
print("\n--- Partitioning ---")
arr = np.array([1, 3, 4, 2, 7, 5, 9, 6])
print("Original array:", arr)
# Partition so that 3rd smallest element is at position 3
partitioned_data = np.partition(arr, 3)
print("After partition (kth=3):", partitioned_data)
print("3rd smallest element is:", partitioned_data[3])

print("\n✓ NumPy Guide Complete!")

--- Memory Layout ---
C-contiguous: True
Fortran-contiguous: False
F-contiguous array: True

--- Memory Views (No Copy) ---
Original array after modifying view: [  1 999   3   4   5]

--- Copy (Independent) ---
Original array after modifying copy: [1 2 3 4 5]

--- Array Comparison ---
arr1 == arr2 (element-wise): [ True  True  True  True  True]
np.array_equal(arr1, arr2): True
np.array_equal(arr1, arr3): False
np.allclose(arr1, arr2): True

--- Masking ---
Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask (3 < arr < 8): [False False False  True  True  True  True False False False]
Masked values: [4 5 6 7]

--- String Operations ---
Original: ['hello' 'world' 'numpy']
Uppercase: ['HELLO' 'WORLD' 'NUMPY']
Replace 'o' with '0': ['hell0' 'w0rld' 'numpy']
String length: [5 5 5]

--- Structured Arrays ---
[('Alice', 25, 55.5) ('Bob', 30, 75.3) ('Charlie', 35, 80.2)]
Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 35]

--- Matrix Operations ---
Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matr

## Quick Reference: Common NumPy Commands

### Array Creation
- `np.array()` - Create from list
- `np.arange()` - Range of evenly spaced values
- `np.linspace()` - Evenly spaced numbers  
- `np.zeros()`, `np.ones()`, `np.full()` - Fill arrays
- `np.eye()` - Identity matrix
- `np.random.rand()`, `np.random.randn()` - Random arrays

### Array Properties
- `.shape` - Dimensions
- `.dtype` - Data type
- `.size` - Total elements
- `.ndim` - Number of dimensions
- `.T` or `.transpose()` - Transpose

### Array Operations
- `np.dot()` or `@` - Matrix multiplication
- `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`
- `**` - Element-wise power
- Broadcasting - automatic shape expansion

### Aggregation Functions
- `np.sum()`, `np.mean()`, `np.median()`, `np.std()`, `np.var()`
- `np.min()`, `np.max()`, `np.argmin()`, `np.argmax()`
- `np.cumsum()`, `np.cumprod()`

### Indexing & Slicing
- `arr[index]` - Single element
- `arr[start:stop:step]` - Slicing
- `arr[arr > 5]` - Boolean indexing
- `arr[[0, 2, 4]]` - Fancy indexing
- `arr[:, 1]` - Column access

### Shape Manipulation
- `np.reshape()` - Change shape
- `np.flatten()`, `np.ravel()` - Flatten
- `np.concatenate()`, `np.stack()`, `np.vstack()`, `np.hstack()`
- `np.split()`, `np.hsplit()`, `np.vsplit()`

### Linear Algebra (np.linalg)
- `np.linalg.dot()` - Matrix multiplication
- `np.linalg.inv()` - Matrix inverse
- `np.linalg.det()` - Determinant
- `np.linalg.eig()` - Eigenvalues/vectors
- `np.linalg.solve()` - Solve linear equations
- `np.linalg.svd()` - Singular value decomposition

### Sorting & Searching
- `np.sort()` - Sort array
- `np.argsort()` - Sort indices
- `np.searchsorted()` - Find insert position
- `np.where()` - Conditional selection

### Mathematical Functions
- Trig: `np.sin()`, `np.cos()`, `np.tan()`
- Logs: `np.log()`, `np.log10()`, `np.log2()`
- Other: `np.sqrt()`, `np.exp()`, `np.abs()`

### File I/O
- `np.save()` / `np.load()` - Binary format (.npy)
- `np.savez()` / `np.load()` - Multiple arrays (.npz)
- `np.savetxt()` / `np.loadtxt()` - Text format (.txt, .csv)

## Practice Exercises

Try these exercises to master NumPy:

In [ ]:
# ===== PRACTICE EXERCISES WITH SOLUTIONS =====

print("=" * 50)
print("EXERCISE 1: Create and manipulate arrays")
print("=" * 50)
# Create a 1D array from 1 to 20, extract every 2nd element, and reshape it
arr = np.arange(1, 21)
result = arr[::2].reshape(5, 2)
print("Original (1-20):", arr)
print("Every 2nd element:", arr[::2])
print("Reshaped to (5, 2):\n", result)

print("\n" + "=" * 50)
print("EXERCISE 2: Statistical analysis")
print("=" * 50)
# Generate 100 random numbers from normal distribution
# Find mean, std, min, max, and count values > 0
data = np.random.normal(loc=0, scale=1, size=100)
print(f"Mean: {np.mean(data):.4f}")
print(f"Std Dev: {np.std(data):.4f}")
print(f"Min: {np.min(data):.4f}")
print(f"Max: {np.max(data):.4f}")
print(f"Count > 0: {np.sum(data > 0)}")

print("\n" + "=" * 50)
print("EXERCISE 3: Matrix operations")
print("=" * 50)
# Create two 3x3 matrices and perform operations
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype=float)
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B:\n", A + B)
print("\nA @ B (matrix multiplication):\n", A @ B)
print("\nElement-wise multiplication:\n", A * B)

print("\n" + "=" * 50)
print("EXERCISE 4: Working with 2D data (like a table)")
print("=" * 50)
# Create a dataset with 5 students and 3 test scores
students = np.array([['Alice', 85, 90, 88],
                     ['Bob', 78, 82, 80],
                     ['Charlie', 92, 95, 90],
                     ['Diana', 88, 91, 89],
                     ['Eve', 95, 97, 96]])
print("Student data:\n", students)
scores = students[:, 1:].astype(float)
print("\nTest scores:\n", scores)
print("Average per student:", np.mean(scores, axis=1))
print("Average per test:", np.mean(scores, axis=0))

print("\n" + "=" * 50)
print("EXERCISE 5: Filtering and masking")
print("=" * 50)
# Create array of numbers and filter based on condition
data = np.array([10, 25, 30, 45, 50, 15, 60, 35, 20, 55])
print("Original data:", data)
# Find values between 25 and 50
mask = (data >= 25) & (data <= 50)
filtered = data[mask]
print("Values between 25 and 50:", filtered)
print("Sum of filtered values:", np.sum(filtered))

print("\n" + "=" * 50)
print("EXERCISE 6: Data normalization")
print("=" * 50)
# Normalize array to [0, 1] range
data = np.array([10, 20, 30, 40, 50])
print("Original data:", data)
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized [0,1]:", normalized)

print("\n" + "=" * 50)
print("EXERCISE 7: Finding patterns")
print("=" * 50)
# Array with duplicates - find unique and count
data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])
unique, counts = np.unique(data, return_counts=True)
print("Data:", data)
print("Unique values:", unique)
print("Counts:", counts)
print("Most common:", unique[np.argmax(counts)])

print("\n" + "=" * 50)
print("EXERCISE 8: Row-wise and column-wise operations")
print("=" * 50)
# Matrix with specific calculations
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Matrix:\n", matrix)
print("Row sums:", np.sum(matrix, axis=1))
print("Column sums:", np.sum(matrix, axis=0))
print("Row products:", np.prod(matrix, axis=1))
print("Column products:", np.prod(matrix, axis=0))

print("\n✓ All exercises completed!")

EXERCISE 1: Create and manipulate arrays
Original (1-20): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Every 2nd element: [ 1  3  5  7  9 11 13 15 17 19]
Reshaped to (5, 2):
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]

EXERCISE 2: Statistical analysis
Mean: -0.0289
Std Dev: 0.9251
Min: -1.9876
Max: 2.4632
Count > 0: 52

EXERCISE 3: Matrix operations
Matrix A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Matrix B:
 [[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]

A + B:
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]

A @ B (matrix multiplication):
 [[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]

Element-wise multiplication:
 [[ 9. 16. 21.]
 [24. 25. 24.]
 [21. 16.  9.]]

EXERCISE 4: Working with 2D data (like a table)
Student data:
 [['Alice' '85' '90' '88']
 ['Bob' '78' '82' '80']
 ['Charlie' '92' '95' '90']
 ['Diana' '88' '91' '89']
 ['Eve' '95' '97' '96']]

Test scores:
 [[85. 90. 88.]
 [78. 82. 80.]
 [92. 95. 90.]
 [88. 91. 89.]
 [95. 97. 96.]]
Average per student: [87.66